/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DestinationCalendarService } from "../destinationCalendar.service";
import { DestinationCalendarCreateInput } from "./DestinationCalendarCreateInput";
import { DestinationCalendarWhereInput } from "./DestinationCalendarWhereInput";
import { DestinationCalendarWhereUniqueInput } from "./DestinationCalendarWhereUniqueInput";
import { DestinationCalendarFindManyArgs } from "./DestinationCalendarFindManyArgs";
import { DestinationCalendarUpdateInput } from "./DestinationCalendarUpdateInput";
import { DestinationCalendar } from "./DestinationCalendar";

export class DestinationCalendarControllerBase {
  constructor(protected readonly service: DestinationCalendarService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DestinationCalendar })
  async create(
    @common.Body() data: DestinationCalendarCreateInput
  ): Promise<DestinationCalendar> {
    return await this.service.create({
      data: {
        ...data,

        booking: data.booking
          ? {
              connect: data.booking,
            }
          : undefined,

        credential: data.credential
          ? {
              connect: data.credential,
            }
          : undefined,

        eventType: data.eventType
          ? {
              connect: data.eventType,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        credential: {
          select: {
            id: true,
          },
        },

        eventType: {
          select: {
            id: true,
          },
        },

        externalId: true,
        id: true,
        integration: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DestinationCalendar] })
  @ApiNestedQuery(DestinationCalendarFindManyArgs)
  async findMany(
    @common.Req() request: Request
  ): Promise<DestinationCalendar[]> {
    const args = plainToClass(DestinationCalendarFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        credential: {
          select: {
            id: true,
          },
        },

        eventType: {
          select: {
            id: true,
          },
        },

        externalId: true,
        id: true,
        integration: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DestinationCalendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async findOne(
    @common.Param() params: DestinationCalendarWhereUniqueInput
  ): Promise<DestinationCalendar | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        credential: {
          select: {
            id: true,
          },
        },

        eventType: {
          select: {
            id: true,
          },
        },

        externalId: true,
        id: true,
        integration: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DestinationCalendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async update(
    @common.Param() params: DestinationCalendarWhereUniqueInput,
    @common.Body() data: DestinationCalendarUpdateInput
  ): Promise<DestinationCalendar | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          booking: data.booking
            ? {
                connect: data.booking,
              }
            : undefined,

          credential: data.credential
            ? {
                connect: data.credential,
              }
            : undefined,

          eventType: data.eventType
            ? {
                connect: data.eventType,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          booking: {
            select: {
              id: true,
            },
          },

          credential: {
            select: {
              id: true,
            },
          },

          eventType: {
            select: {
              id: true,
            },
          },

          externalId: true,
          id: true,
          integration: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DestinationCalendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async delete(
    @common.Param() params: DestinationCalendarWhereUniqueInput
  ): Promise<DestinationCalendar | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          booking: {
            select: {
              id: true,
            },
          },

          credential: {
            select: {
              id: true,
            },
          },

          eventType: {
            select: {
              id: true,
            },
          },

          externalId: true,
          id: true,
          integration: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
